import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Logo from './logo.svg';
import './globals.css';

// components
import NavBar from './components/nav/nav';
import Footer from './components/footer/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Colosseum Combat',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.svg',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
